# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-03 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='cover',
            field=models.CharField(max_length=200),
        ),
    ]
