# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160703_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='cover',
            field=models.ImageField(upload_to='cover/%Y/%m/%d'),
        ),
    ]
