# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-29 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='You name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('introduction', models.TextField(blank=True, verbose_name='Introduction of yourself')),
            ],
        ),
    ]
