# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-28 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=150)),
                ('from_date', models.DateField(verbose_name='Since')),
                ('to_date', models.DateField(verbose_name='To')),
                ('detail', models.TextField(verbose_name='Detail Description')),
            ],
            options={
                'ordering': ['from_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=150)),
                ('from_date', models.DateField(verbose_name='Since')),
                ('to_date', models.DateField(verbose_name='To')),
                ('detail', models.TextField(verbose_name='Detail Description')),
            ],
            options={
                'ordering': ['from_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_item', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Profile'),
        ),
        migrations.AddField(
            model_name='achievements',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Profile'),
        ),
    ]
