# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-03 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'ordering': ['to_date']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['to_date']},
        ),
    ]
